version: '3'
services:
  app:
    container_name: adrc_api
    build: .
    image: api-node
    command: npm run start:dev && npm run typeorm migration:run
    volumes:
      - ./:/usr/src/app 
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Veno@2021
      DB_NAME: adrc

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Veno@2021
      POSTGRES_DB: adrc
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgadmindata:
  
networks:
 app-network:
    driver: bridge
